### ISSUE TITLE
about @only.linux

### ISSUE THREAD

**Issue by brunobell** [russianidiot/only.py#1]
I reckon that you might have neglected the situation nowadays when the return string of linux platform is linux2, here is my test, it failed and raised an OSError, which is not the case:
`➜  ~ uname -a
Linux amor 4.5.6-200.fc23.x86_64 #1 SMP Wed Jun 1 21:28:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
`➜  ~ python -c "import sys;print sys.platform;"`
`linux2`

**Comment by andrewpetrochenkov** [comment]
thx, fixed
